# Generated by Django 3.2.4 on 2021-06-29 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BPLA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
                ('capacity', models.SmallIntegerField(blank=True, null=True)),
                ('speed', models.FloatField(blank=True, null=True)),
                ('latitude', models.CharField(max_length=15, null=True)),
                ('longitude', models.CharField(max_length=15, null=True)),
                ('azimuth', models.FloatField(blank=True, null=True)),
                ('cur_departure', models.IntegerField(blank=True, null=True)),
                ('cur_destination', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bpla',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HUB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
                ('workload', models.FloatField(blank=True, null=True)),
                ('latitude', models.CharField(max_length=15, null=True)),
                ('longitude', models.CharField(max_length=15, null=True)),
                ('ip', models.CharField(max_length=15, null=True)),
            ],
            options={
                'db_table': 'hub',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ORDER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backend_id', models.IntegerField(blank=True, null=True)),
                ('track', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'order',
                'managed': True,
            },
        ),
    ]
