# Generated by Django 3.2.5 on 2021-07-11 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hub',
            name='backend_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='bpla',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
