# Generated by Django 3.2.5 on 2021-07-16 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210712_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='bpla',
            name='lat_delta',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bpla',
            name='long_delta',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
