# Generated by Django 3.2.4 on 2021-06-29 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BPLA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_number', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=10)),
                ('capacity', models.SmallIntegerField(blank=True, null=True)),
                ('speed', models.FloatField(blank=True, null=True)),
                ('latitude', models.CharField(max_length=15, null=True)),
                ('longitude', models.CharField(max_length=15, null=True)),
                ('azimuth', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bpla',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HUB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
                ('workload', models.FloatField(blank=True, null=True)),
                ('latitude', models.CharField(max_length=15, null=True)),
                ('longitude', models.CharField(max_length=15, null=True)),
            ],
            options={
                'db_table': 'hub',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ORDER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(blank=True, null=True)),
                ('track', models.TextField(blank=True, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('bpla', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='deliveryAPI.bpla')),
                ('cur_departure', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cur_departure', to='deliveryAPI.hub')),
                ('cur_destination', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cur_destination', to='deliveryAPI.hub')),
            ],
            options={
                'db_table': 'order',
                'managed': True,
            },
        ),
    ]
