# Generated by Django 3.2.5 on 2021-07-13 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryAPI', '0004_auto_20210713_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bpla',
            name='lat_delta',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bpla',
            name='long_delta',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
