# Generated by Django 3.2.5 on 2021-07-14 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryAPI', '0006_order_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='bpla',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='deliveryAPI.bpla'),
        ),
    ]
