# Generated by Django 3.2.5 on 2021-07-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryAPI', '0007_alter_order_bpla'),
    ]

    operations = [
        migrations.CreateModel(
            name='STATISTICS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_weight_delivered', models.IntegerField(blank=True, null=True)),
                ('current_uav_quantity', models.IntegerField(blank=True, null=True)),
                ('total_distance_travelled', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'statistics',
                'managed': True,
            },
        ),
    ]
